baseurl = "https://docardoso.github.io/"
title = "Douglas O. Cardoso"
copyright = "&copy; 2017 Douglas O. Cardoso"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "pt"
defaultContentLanguageInSubdir = false

[blackfriday]
  #hrefTargetBlank = true

[params]
   name = "Douglas O. Cardoso"
   organization = "CEFET-RJ Petrópolis"
   organization_url = "http://www.cefet-rj.br/"
   avatar = "foto_quadrada.jpg"
   email = "douglas.cardoso@cefet-rj.br"

[[params.social]]
 icon = "envelope"
 icon_pack = "fa"
 link = "mailto:douglas.cardoso@cefet-rj.br"

[[params.social]]
 icon = "google-scholar"
 icon_pack = "ai"
 link = "https://scholar.google.com.br/citations?user=i88U02AAAAAJ"

[[params.social]]
 icon = "orcid"
 icon_pack = "ai"
 link = "http://orcid.org/0000-0002-1932-334X"

[[params.social]]
 icon = "researchgate"
 icon_pack = "ai"
 link = "https://www.researchgate.net/profile/Douglas_Cardoso"

[[params.social]]
 icon = "github"
 icon_pack = "fa"
 link = "https://github.com/docardoso"

[[params.social]]
 icon = "address-card"
 icon_pack = "fa"
 link = "http://buscacv.cnpq.br/buscacv/#/espelho?nro_id_cnpq_cp_s=9438219886705967"

[languages]
[languages.pt]
   role = "Professor"
   address = "Laboratório MARC, CEFET-RJ Petrópolis, Rio de Janeiro, Brasil"
   office_hours = "Terças, das 14:00 às 17:00; ou conforme agendamento"

[languages.en]
   role = "Assistant Professor"
   address = "MARC Lab, CEFET-RJ Petrópolis, Rio de Janeiro, Brazil"
   office_hours = "Tuesdays, 14:00 to 17:00; or by appointment"
   phone = ""
   skype = ""
   telegram = ""

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]


[[languages.en.menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[languages.pt.menu.main]]
  name = "Início"
  url = "#about"
  weight = 1

[[languages.en.menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6

[[languages.pt.menu.main]]
  name = "Contato"
  url = "#contact"
  weight = 6

[[languages.pt.menu.main]]
  name = "In English"
  pre = "<i class='fa fa-language'></i>"
  url = "/en"
  weight = 10

[[languages.en.menu.main]]
  name = "Em Português"
  pre = "<i class='fa fa-language'></i>"
  url = "../pt"
  weight = 10

[[languages.pt.menu.main]]
  name = "Cursos"
  url = "#cursos"
  weight = 4

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
